controller_names:
  - arm_controller
  - gripper_controller

arm_controller:
  type: FollowJointTrajectory
  action_ns: follow_joint_trajectory
  default: true
  joints:
    - manipulator/joint1
    - manipulator/joint2
    - manipulator/joint3
    - manipulator/joint4
gripper_controller:
  type: GripperCommand
  action_ns: gripper_cmd
  default: true
  joints:
    - manipulator/gripper_left_joint
